"""C++ — Buffer Overflow / Memory Safety sinks."""

from app.scanner.sink.types import SinkRule

VULNERABILITY = "buffer_overflow"

_CPP = [".cpp", ".cc", ".cxx", ".cp", ".hpp", ".hh", ".hxx", ".h"]

RULES = [
    SinkRule(
        id="cpp-buf-strcpy",
        function="std::strcpy / ::strcpy",
        call_regex=r"\b(?:std\s*::\s*)?strcpy\s*\(",
        description="strcpy without length — overruns dst.",
        argument_roles=["dst", "src"],
        extensions=_CPP,
        severity="critical",
    ),
    SinkRule(
        id="cpp-buf-strcat",
        function="std::strcat",
        call_regex=r"\b(?:std\s*::\s*)?strcat\s*\(",
        description="strcat appends without bounds.",
        argument_roles=["dst", "src"],
        extensions=_CPP,
        severity="critical",
    ),
    SinkRule(
        id="cpp-buf-sprintf",
        function="std::sprintf",
        call_regex=r"\b(?:std\s*::\s*)?sprintf\s*\(",
        description="sprintf has no destination length.",
        argument_roles=["buf", "format", "args"],
        extensions=_CPP,
        severity="critical",
    ),
    SinkRule(
        id="cpp-buf-gets",
        function="gets(...)",
        call_regex=r"\bgets\s*\(",
        description="gets() removed in C++14 but still seen in legacy code.",
        argument_roles=["buf"],
        extensions=_CPP,
        severity="critical",
    ),
    SinkRule(
        id="cpp-buf-c-array-index",
        function="raw array[index] with attacker-controlled index",
        call_regex=r"\[\s*[a-zA-Z_]\w*\s*\]",
        description="Indexing raw array with user value — review bounds.",
        argument_roles=[],
        extensions=_CPP,
        severity="low",
    ),
    SinkRule(
        id="cpp-buf-vector-at-vs-bracket",
        function="std::vector::operator[] with user index",
        call_regex=r"\.\s*operator\s*\[\s*\]\s*\(",
        description="vector::operator[] is UB on OOB; use .at() for bounds check.",
        argument_roles=[],
        extensions=_CPP,
        severity="low",
    ),
    SinkRule(
        id="cpp-buf-reinterpret-cast",
        function="reinterpret_cast<T*>(buf)",
        call_regex=r"\breinterpret_cast\s*<",
        description="reinterpret_cast often defeats type/size checks.",
        argument_roles=[],
        extensions=_CPP,
        severity="medium",
    ),
    SinkRule(
        id="cpp-buf-memcpy",
        function="std::memcpy(dst, src, len)",
        call_regex=r"\b(?:std\s*::\s*)?memcpy\s*\(",
        description="memcpy with user-influenced length.",
        argument_roles=["dst", "src", "n"],
        extensions=_CPP,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="cpp-buf-memmove",
        function="std::memmove",
        call_regex=r"\b(?:std\s*::\s*)?memmove\s*\(",
        description="memmove with attacker-controlled length.",
        argument_roles=["dst", "src", "n"],
        extensions=_CPP,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="cpp-buf-stringstream-read",
        function="istream::read(buf, n) without size check",
        call_regex=r"\.\s*read\s*\(",
        description="istream::read with user-controlled count.",
        argument_roles=["s", "n"],
        extensions=_CPP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="cpp-buf-cin-unbounded",
        function="std::cin >> char_array",
        call_regex=r"\bstd\s*::\s*cin\s*>>",
        description="cin >> char[] is unbounded.",
        argument_roles=[],
        extensions=_CPP,
        severity="high",
    ),
    SinkRule(
        id="cpp-buf-scanf",
        function="std::scanf with %s",
        call_regex=r"\b(?:std\s*::\s*)?(?:f|s)?scanf\s*\(",
        description="bare %s overflows buf.",
        argument_roles=[],
        extensions=_CPP,
        severity="high",
    ),
    SinkRule(
        id="cpp-buf-new-with-user-size",
        function="new T[userSize]",
        call_regex=r"\bnew\s+[\w:]+\s*\[",
        description="Array new with attacker-controlled size = OOM/DoS or size==0.",
        argument_roles=[],
        extensions=_CPP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="cpp-buf-placement-new",
        function="placement new (no size guarantee)",
        call_regex=r"\bnew\s*\(\s*[^)]+\)",
        description="Placement new — caller must ensure buf is large enough.",
        argument_roles=[],
        extensions=_CPP,
        severity="medium",
    ),
    SinkRule(
        id="cpp-buf-printf-fmt-tainted",
        function="printf(userFmt, ...)",
        call_regex=r"\b(?:std\s*::\s*)?(?:printf|fprintf|sprintf|snprintf)\s*\(",
        description="Format string vulnerability when format comes from user input.",
        argument_roles=[],
        extensions=_CPP,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="cpp-buf-stoi-uncaught",
        function="std::stoi / stol / stoul on user input",
        call_regex=r"\bstd\s*::\s*sto(?:i|l|ll|ul|ull|f|d|ld)\s*\(",
        description="std::stoi throws on bad input; uncaught will terminate or be size-confused.",
        argument_roles=[],
        extensions=_CPP,
        severity="low",
    ),
]
