"""C — Buffer Overflow / Memory Safety sinks (CWE-119, CWE-120, CWE-121, CWE-122, CWE-787)."""

from app.scanner.sink.types import SinkRule

VULNERABILITY = "buffer_overflow"

_C = [".c", ".h"]

RULES = [
    SinkRule(
        id="c-buf-strcpy",
        function="strcpy(dst, src)",
        call_regex=r"\bstrcpy\s*\(",
        description="strcpy has no length check; overruns dst when src exceeds buffer size.",
        argument_roles=["dst", "src"],
        extensions=_C,
        severity="critical",
    ),
    SinkRule(
        id="c-buf-strcat",
        function="strcat(dst, src)",
        call_regex=r"\bstrcat\s*\(",
        description="strcat appends without bounds — classic stack overflow.",
        argument_roles=["dst", "src"],
        extensions=_C,
        severity="critical",
    ),
    SinkRule(
        id="c-buf-gets",
        function="gets(buf)",
        call_regex=r"\bgets\s*\(",
        description="gets() reads unbounded line into buf — always exploitable.",
        argument_roles=["buf"],
        extensions=_C,
        severity="critical",
    ),
    SinkRule(
        id="c-buf-sprintf",
        function="sprintf(buf, fmt, ...)",
        call_regex=r"\bsprintf\s*\(",
        description="sprintf has no destination length — use snprintf.",
        argument_roles=["buf", "format", "args"],
        extensions=_C,
        severity="critical",
    ),
    SinkRule(
        id="c-buf-vsprintf",
        function="vsprintf(buf, fmt, ap)",
        call_regex=r"\bvsprintf\s*\(",
        description="vsprintf — same overflow risk as sprintf.",
        argument_roles=["buf", "format", "ap"],
        extensions=_C,
        severity="critical",
    ),
    SinkRule(
        id="c-buf-scanf-string",
        function="scanf(\"%s\", buf)",
        call_regex=r"\bscanf\s*\(",
        description="scanf %s without width specifier overflows buf.",
        argument_roles=["format", "args"],
        extensions=_C,
        severity="high",
    ),
    SinkRule(
        id="c-buf-fscanf-string",
        function="fscanf(stream, \"%s\", buf)",
        call_regex=r"\bf?scanf\s*\(",
        description="fscanf/sscanf with bare %s overflows buf.",
        argument_roles=["stream", "format", "args"],
        extensions=_C,
        severity="high",
    ),
    SinkRule(
        id="c-buf-memcpy-dynamic-len",
        function="memcpy(dst, src, len)",
        call_regex=r"\bmemcpy\s*\(",
        description="memcpy with user-influenced length — OOB write.",
        argument_roles=["dst", "src", "n"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-buf-memmove-dynamic-len",
        function="memmove(dst, src, len)",
        call_regex=r"\bmemmove\s*\(",
        description="memmove with attacker-controlled length.",
        argument_roles=["dst", "src", "n"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-buf-alloca-dynamic-size",
        function="alloca(userSize)",
        call_regex=r"\balloca\s*\(",
        description="alloca with dynamic size — stack pivot / SO.",
        argument_roles=["size"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-buf-stpcpy",
        function="stpcpy(dst, src)",
        call_regex=r"\bstpcpy\s*\(",
        description="stpcpy is unbounded like strcpy.",
        argument_roles=["dst", "src"],
        extensions=_C,
        severity="high",
    ),
    SinkRule(
        id="c-buf-getwd",
        function="getwd(buf)",
        call_regex=r"\bgetwd\s*\(",
        description="getwd() obsolete — fixed buf size = overflow. Use getcwd.",
        argument_roles=["buf"],
        extensions=_C,
        severity="high",
    ),
    SinkRule(
        id="c-buf-realpath-no-null",
        function="realpath(path, NULL_or_buf)",
        call_regex=r"\brealpath\s*\(",
        description="realpath with a fixed PATH_MAX buf — overflow if path > PATH_MAX.",
        argument_roles=["path", "resolved"],
        extensions=_C,
        severity="medium",
    ),
    SinkRule(
        id="c-buf-strncpy-no-null",
        function="strncpy without explicit null-terminate",
        call_regex=r"\bstrncpy\s*\(",
        description="strncpy doesn't null-terminate when src ≥ n — later string ops overrun.",
        argument_roles=["dst", "src", "n"],
        extensions=_C,
        severity="medium",
    ),
    SinkRule(
        id="c-buf-strncat-off-by-one",
        function="strncat(dst, src, n)",
        call_regex=r"\bstrncat\s*\(",
        description="strncat's n is *remaining* space minus 1 — common off-by-one source.",
        argument_roles=["dst", "src", "n"],
        extensions=_C,
        severity="medium",
    ),
    SinkRule(
        id="c-buf-printf-tainted-fmt",
        function="printf(userInput)",
        call_regex=r"\b(?:printf|fprintf|dprintf|vprintf|vfprintf)\s*\(",
        description="Format string vuln when the format itself comes from user input.",
        argument_roles=["format", "args"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-buf-syslog-tainted-fmt",
        function="syslog(prio, userFmt)",
        call_regex=r"\bsyslog\s*\(",
        description="Format string vulnerability via syslog format argument.",
        argument_roles=["priority", "format", "args"],
        extensions=_C,
        severity="medium",
        require_dynamic=True,
    ),
]
