"""C — Path Traversal sinks (CWE-22, CWE-23)."""

from app.scanner.sink.types import SinkRule

VULNERABILITY = "path_traversal"

_C = [".c", ".h"]

RULES = [
    SinkRule(
        id="c-path-fopen",
        function="fopen(path, mode)",
        call_regex=r"\bfopen(?:64)?\s*\(",
        description="fopen with dynamic path.",
        argument_roles=["pathname", "mode"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-open",
        function="open(path, flags)",
        call_regex=r"\bopen(?:at|64)?\s*\(",
        description="POSIX open with dynamic path / flags.",
        argument_roles=["pathname", "flags", "mode"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-creat",
        function="creat(path, mode)",
        call_regex=r"\bcreat\s*\(",
        description="creat() with dynamic path.",
        argument_roles=["pathname", "mode"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-unlink",
        function="unlink / remove / rmdir",
        call_regex=r"\b(?:unlink|unlinkat|remove|rmdir)\s*\(",
        description="Deletion of user-controlled path.",
        argument_roles=["pathname"],
        extensions=_C,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-rename",
        function="rename / renameat",
        call_regex=r"\brename(?:at|at2)?\s*\(",
        description="Rename file with user-supplied src/dst.",
        argument_roles=["oldpath", "newpath"],
        extensions=_C,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-symlink",
        function="symlink / link / linkat",
        call_regex=r"\b(?:symlink|link|symlinkat|linkat)\s*\(",
        description="Symlink/hardlink creation with attacker-controlled target.",
        argument_roles=["target", "linkpath"],
        extensions=_C,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-readlink",
        function="readlink(path, buf, size)",
        call_regex=r"\breadlinkat?\s*\(",
        description="readlink with dynamic path — TOCTOU + traversal.",
        argument_roles=["pathname", "buf", "bufsiz"],
        extensions=_C,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-access",
        function="access(path, mode)",
        call_regex=r"\baccess\s*\(",
        description="access() before open is classic TOCTOU.",
        argument_roles=["pathname", "mode"],
        extensions=_C,
        severity="low",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-chdir",
        function="chdir(path)",
        call_regex=r"\bchdir\s*\(",
        description="chdir with user input — escape from intended directory.",
        argument_roles=["path"],
        extensions=_C,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="c-path-chroot",
        function="chroot(path)",
        call_regex=r"\bchroot\s*\(",
        description="chroot is not a security boundary; flagged for review.",
        argument_roles=["path"],
        extensions=_C,
        severity="low",
    ),
]
