"""JavaScript — XSS sinks (CWE-79). Both DOM XSS and Node.js response XSS."""

from app.scanner.sink.types import SinkRule

VULNERABILITY = "xss"

_JS = [".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".vue", ".svelte"]

RULES = [
    SinkRule(
        id="js-xss-innerhtml",
        function="element.innerHTML = value",
        call_regex=r"\.\s*innerHTML\s*=",
        description="Assigning user data to innerHTML executes embedded scripts.",
        argument_roles=["html"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-outerhtml",
        function="element.outerHTML = value",
        call_regex=r"\.\s*outerHTML\s*=",
        description="outerHTML assignment renders untrusted HTML.",
        argument_roles=["html"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-insertadjacenthtml",
        function="element.insertAdjacentHTML",
        call_regex=r"\.\s*insertAdjacentHTML\s*\(",
        description="insertAdjacentHTML inserts HTML at a specific position.",
        argument_roles=["position", "text"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-document-write",
        function="document.write / writeln",
        call_regex=r"\bdocument\.\s*write(?:ln)?\s*\(",
        description="document.write writes raw HTML to the page.",
        argument_roles=["markup"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-jquery-html",
        function="$(...).html(value)",
        call_regex=r"\$\([^)]*\)\s*\.\s*html\s*\(",
        description="jQuery .html(value) is equivalent to setting innerHTML.",
        argument_roles=["html"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-jquery-append-prepend",
        function="$.append/prepend(html)",
        call_regex=r"\$\([^)]*\)\s*\.\s*(?:append|prepend|after|before|replaceWith)\s*\(",
        description="jQuery DOM-insertion methods accept HTML strings.",
        argument_roles=["content"],
        extensions=_JS,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="js-xss-react-dangerouslysetinnerhtml",
        function="dangerouslySetInnerHTML",
        call_regex=r"\bdangerouslySetInnerHTML\s*=\s*\{",
        description="React dangerouslySetInnerHTML bypasses JSX auto-escape.",
        argument_roles=["__html"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-vue-vhtml",
        function="v-html=\"...\"",
        call_regex=r"\bv-html\s*=",
        description="Vue v-html renders raw HTML expression.",
        argument_roles=["expression"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-angular-bypass",
        function="DomSanitizer.bypassSecurityTrustHtml",
        call_regex=r"\bbypassSecurityTrust(?:Html|Script|Url|ResourceUrl|Style)\s*\(",
        description="Angular DomSanitizer bypass disables sanitization.",
        argument_roles=["value"],
        extensions=_JS,
        severity="critical",
    ),
    SinkRule(
        id="js-xss-express-res-send",
        function="res.send / res.write",
        call_regex=r"\bres\s*\.\s*(?:send|write|end)\s*\(",
        description="Express response writers with concatenated HTML.",
        argument_roles=["body"],
        extensions=_JS,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="js-xss-eval-location-hash",
        function="window.location.hash → DOM sink",
        call_regex=r"location\.\s*(?:hash|search|href)",
        description="DOM source typically piped into a sink; flag for review.",
        argument_roles=[],
        extensions=_JS,
        severity="low",
    ),
    SinkRule(
        id="js-xss-document-location",
        function="document.location = value",
        call_regex=r"\bdocument\.location\s*=",
        description="Setting document.location to user input enables javascript: scheme exec.",
        argument_roles=["url"],
        extensions=_JS,
        severity="high",
    ),
    SinkRule(
        id="js-xss-handlebars-safestring",
        function="new Handlebars.SafeString(value)",
        call_regex=r"\bnew\s+Handlebars\.\s*SafeString\s*\(",
        description="SafeString tells Handlebars the string is pre-escaped HTML.",
        argument_roles=["value"],
        extensions=_JS,
        severity="high",
    ),
    SinkRule(
        id="js-xss-mustache-triple",
        function="Mustache {{{ value }}}",
        call_regex=r"\{\{\{[^}]+\}\}\}",
        description="Mustache triple-stache prints raw HTML.",
        argument_roles=["expression"],
        extensions=[".mustache", ".hbs", ".html"],
        severity="high",
    ),
    SinkRule(
        id="js-xss-ejs-unescaped",
        function="EJS <%- value %>",
        call_regex=r"<%-\s*[a-zA-Z_]",
        description="EJS <%- ... %> outputs unescaped.",
        argument_roles=["expression"],
        extensions=[".ejs", ".html"],
        severity="high",
    ),
]
