"""PHP — SQL Injection sinks (CWE-89)."""

from app.scanner.sink.types import SinkRule

VULNERABILITY = "sql_injection"

_PHP = [".php", ".phtml", ".inc"]

RULES = [
    SinkRule(
        id="php-sql-mysqli-query",
        function="mysqli_query",
        call_regex=r"\bmysqli_query\s*\(",
        description="Executes a raw SQL string through mysqli_query.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-mysqli-real-query",
        function="mysqli_real_query",
        call_regex=r"\bmysqli_real_query\s*\(",
        description="Executes a raw SQL string via mysqli_real_query.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-mysqli-multi",
        function="mysqli_multi_query",
        call_regex=r"\bmysqli_multi_query\s*\(",
        description="Executes one or more SQL statements; allows stacked queries.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-mysql-query-legacy",
        function="mysql_query",
        call_regex=r"\bmysql_query\s*\(",
        description="Legacy mysql_query is removed in PHP 7+ but still seen in old code.",
        argument_roles=["query", "connection"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-pdo-query",
        function="PDO::query",
        call_regex=r"->\s*query\s*\(",
        description="$pdo->query() executes raw SQL; flagged when arg looks dynamic.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-pdo-exec",
        function="PDO::exec",
        call_regex=r"->\s*exec\s*\(",
        description="$pdo->exec() executes raw SQL; flagged when arg looks dynamic.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="high",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-pdo-prepare-dynamic",
        function="PDO::prepare",
        call_regex=r"->\s*prepare\s*\(",
        description="$pdo->prepare with concatenated SQL still allows injection.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-mysqli-prepare-dynamic",
        function="mysqli::prepare",
        call_regex=r"->\s*prepare\s*\(",
        description="mysqli::prepare with concatenated SQL still allows injection.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-doctrine-query",
        function="Doctrine::query/createQuery",
        call_regex=r"->\s*(?:createQuery|getQuery|prepare|exec|query)\s*\(",
        description="Doctrine ORM query construction taking raw DQL/SQL.",
        argument_roles=["dql_or_sql"],
        extensions=_PHP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-mssql-query",
        function="mssql_query",
        call_regex=r"\bmssql_query\s*\(",
        description="Legacy MS SQL Server query function.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-pg-query",
        function="pg_query",
        call_regex=r"\bpg_query\s*\(",
        description="PostgreSQL pg_query executing raw SQL.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="critical",
    ),
    SinkRule(
        id="php-sql-sqlite-query",
        function="sqlite_query",
        call_regex=r"\bsqlite_query\s*\(",
        description="Legacy SQLite query function.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="high",
    ),
    SinkRule(
        id="php-sql-sqlite3-exec",
        function="SQLite3::exec/query",
        call_regex=r"->\s*(?:exec|query|querySingle)\s*\(",
        description="SQLite3 raw query executor.",
        argument_roles=["query"],
        extensions=_PHP,
        severity="medium",
        require_dynamic=True,
    ),
    SinkRule(
        id="php-sql-oci-parse",
        function="oci_parse",
        call_regex=r"\boci_parse\s*\(",
        description="Oracle OCI parse with concatenated SQL.",
        argument_roles=["connection", "query"],
        extensions=_PHP,
        severity="high",
        require_dynamic=True,
    ),
]
